# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-08 15:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TImgaeInfo',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('img_id', models.CharField(max_length=10, unique=True)),
                ('location', models.CharField(max_length=128)),
                ('description', models.CharField(blank=True, max_length=128, null=True)),
                ('user_name', models.CharField(max_length=30)),
                ('mtime', models.DateTimeField(auto_now=True)),
                ('ctime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 't_imgae_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.URLField(blank=True)),
                ('picture', models.ImageField(blank=True, upload_to='profile_images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
